const screens=[...document.querySelectorAll('.screen')],show=id=>{screens.forEach(s=>s.classList.toggle('active',s.id===id));location.hash=id};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));addEventListener('hashchange',()=>show(location.hash.slice(1)||'home'));document.querySelector('.backHome').onclick=e=>{e.preventDefault();show('home')};
let player='Murid',score=24;document.querySelector('#joinForm').onsubmit=e=>{e.preventDefault();player=document.querySelector('#studentName').value.trim();document.querySelector('#lobbyName').textContent=player;document.querySelector('#matchName').textContent=player;document.querySelector('#scoreName').childNodes[0].textContent=player+' ';show('lobby')};
const values={A:1,B:3,C:3,D:2,E:1,F:4,G:2,H:4,I:1,J:8,K:5,L:1,M:3,N:1,O:1,P:3,Q:10,R:1,S:1,T:1,U:1,V:4,W:4,X:8,Y:4,Z:10},accepted=new Set(['SAYA','SAYANG','KUCING','BUKU','SEKOLAH','GURU','MURID','KELAS','MAIN','KATA','BAHASA']),input=document.querySelector('#wordInput'),preview=document.querySelector('#wordScore'),message=document.querySelector('#wordMessage'),challenge=document.querySelector('#challengeBtn');
for(let i=0;i<81;i++){const c=document.createElement('span');c.textContent=i===40?'★':i%13===0?'DW':'';c.className=i===40?'star':i%13===0?'bonus':'';document.querySelector('#board').append(c)}
['S','A','Y','A','N','G','U'].forEach(l=>{const b=document.createElement('button');b.innerHTML=`${l}<small>${values[l]}</small>`;b.onclick=()=>{input.value+=l;input.dispatchEvent(new Event('input'))};document.querySelector('#rack').append(b)});const calc=w=>[...w].reduce((n,l)=>n+(values[l]||0),0);input.oninput=()=>{input.value=input.value.toUpperCase().replace(/[^A-Z]/g,'');preview.textContent=calc(input.value)+' mata'};document.querySelector('#submitWord').onclick=()=>{const w=input.value;if(!w)return;if(accepted.has(w)){const pts=calc(w);score+=pts;document.querySelector('#myScore').textContent=score;message.textContent=`✓ ${w} diterima · +${pts} mata`;input.value='';preview.textContent='0 mata';challenge.hidden=true}else{message.textContent=`${w} belum ditemui dalam kamus`;challenge.hidden=false}};document.querySelector('#startMatches').onclick=e=>{e.target.textContent=e.target.textContent.includes('Mulakan')?'Jeda Permainan':'Mulakan Padanan';document.querySelector('#matchStatus').textContent=e.target.textContent.includes('Jeda')?'● Sedang berlangsung':'◷ Belum dimulakan'};
const cfg=window.SAHIBBA_FIREBASE_CONFIG||{},configured=Object.values(cfg).every(Boolean),superEmail='mradnanmahmud@gmail.com',permitted=email=>email===superEmail||email.endsWith('@moe.edu.sg')||email.endsWith('@schools.gov.sg');if(!configured)document.querySelector('#configNote').hidden=false;
if(configured){
  const {initializeApp}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),{getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),{getFirestore,doc,setDoc,serverTimestamp}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js'),app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});
  async function enterTeacher(user){const email=(user.email||'').toLowerCase();if(!permitted(email)){await signOut(auth);throw Error('Pendaftaran hanya untuk akaun @moe.edu.sg atau @schools.gov.sg.')}const role=email===superEmail?'superuser':'teacher';await setDoc(doc(db,'teachers',user.uid),{uid:user.uid,email,displayName:user.displayName||'Guru',role,lastLoginAt:serverTimestamp()}, {merge:true});document.querySelector('#teacherName').textContent=user.displayName||'Guru';document.querySelector('#teacherEmail').textContent=email;const title=document.querySelector('.dashboard h1');title.textContent=role==='superuser'?'Pusat Superuser & Kelas Saya':'Ruang Kelas Saya';let badge=document.querySelector('#roleBadge');if(!badge){badge=document.createElement('p');badge.id='roleBadge';badge.className='eyebrow';title.after(badge)}badge.textContent=role==='superuser'?'SUPERUSER · AKSES SEMUA GURU':'AKAUN GURU · DATA PERIBADI';show('dashboard')}
  document.querySelector('#googleLogin').onclick=async()=>{try{const r=await signInWithPopup(auth,provider);await enterTeacher(r.user)}catch(e){const p=document.querySelector('#authError');p.hidden=false;p.textContent=e.message}};
  onAuthStateChanged(auth,u=>{if(u&&permitted((u.email||'').toLowerCase())&&location.hash==='#dashboard')enterTeacher(u).catch(()=>show('teacher'))});document.querySelector('#logout').onclick=async()=>{await signOut(auth);show('home')};
}else document.querySelector('#googleLogin').onclick=()=>document.querySelector('#configNote').hidden=false;
if(location.hash)show(location.hash.slice(1));
