const style=document.createElement('link');style.rel='stylesheet';style.href='dashboard.css';document.head.append(style);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const quickMenu=$('#quickMenu'),menuButton=$('#menuButton');
const show=id=>{$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));location.hash=id;quickMenu.hidden=true;menuButton.setAttribute('aria-expanded','false')};
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));addEventListener('hashchange',()=>show(location.hash.slice(1)||'home'));$('.backHome').onclick=e=>{e.preventDefault();show('home')};
menuButton.onclick=()=>{quickMenu.hidden=!quickMenu.hidden;menuButton.setAttribute('aria-expanded',String(!quickMenu.hidden))};$('#menuDashboard').onclick=()=>show('dashboard');
let player='Murid',score=24,joinSession=null;
$('#joinForm').onsubmit=async e=>{e.preventDefault();player=$('#studentName').value.trim();const code=e.currentTarget.querySelector('.codeInput').value.trim();if(joinSession)try{await joinSession(code,player)}catch(err){alert(err.message);return}$('#lobbyName').textContent=player;$('#matchName').textContent=player;$('#scoreName').childNodes[0].textContent=player+' ';show('lobby')};
const values={A:1,B:3,C:3,D:2,E:1,F:4,G:2,H:4,I:1,J:8,K:5,L:1,M:3,N:1,O:1,P:3,Q:10,R:1,S:1,T:1,U:1,V:4,W:4,X:8,Y:4,Z:10},accepted=new Set(['SAYA','SAYANG','KUCING','BUKU','SEKOLAH','GURU','MURID','KELAS','MAIN','KATA','BAHASA']);
const boardSize=15,center=112,boardState=Array(225).fill(null),pending=new Map(),bag='AAAAAAAAAAAAAAAAAAAAABBCCCCDDDDEEEEEEEEEEEEEFFFFGGGGGHHHHHIIIIIIIIIIIJKKKKLLLLLMMMMMMNNNNNNNNNOOOOOOOPPPPQRSSSSSSSSTTTTTTTTTUUUUUUVVWWXYYZ'.split(''),premium={0:'TW',7:'TW',14:'TW',105:'TW',119:'TW',210:'TW',217:'TW',224:'TW',16:'DW',32:'DW',48:'DW',64:'DW',160:'DW',176:'DW',192:'DW',208:'DW',3:'DL',11:'DL',45:'DL',59:'DL',165:'DL',179:'DL',213:'DL',221:'DL',20:'TL',24:'TL',76:'TL',80:'TL',144:'TL',148:'TL',200:'TL',204:'TL'};let rackLetters=['S','A','Y','A','N','G','U'],selected=null;
const draw=()=>bag.length?bag.splice(Math.floor(Math.random()*bag.length),1)[0]:'A',tileHTML=l=>`${l}<small>${values[l]}</small>`;
function renderRack(){const rack=$('#rack');rack.innerHTML='';rackLetters.forEach((l,i)=>{const b=document.createElement('button');b.innerHTML=tileHTML(l);b.classList.toggle('selected',i===selected);b.onclick=()=>{selected=selected===i?null:i;renderRack()};rack.append(b)})}
function renderBoard(){const board=$('#board');board.innerHTML='';for(let i=0;i<225;i++){const c=document.createElement('button'),l=pending.get(i)?.letter||boardState[i];c.dataset.cell=i;if(l){c.innerHTML=tileHTML(l);c.className='placedTile'+(pending.has(i)?' pending':'')}else{c.textContent=i===center?'★':premium[i]||'';c.className=i===center?'star':premium[i]?.toLowerCase()||''}c.onclick=()=>placeTile(i);board.append(c)}}
function placeTile(i){if(boardState[i])return;if(pending.has(i)){rackLetters.push(pending.get(i).letter);pending.delete(i);selected=null;renderBoard();renderRack();previewMove();return}if(selected===null)return;const letter=rackLetters[selected];pending.set(i,{letter});rackLetters.splice(selected,1);selected=null;renderBoard();renderRack();previewMove()}
const lineWord=(start,step)=>{let i=start;while(i-step>=0&&i-step<225&&(step===15||Math.floor((i-step)/15)===Math.floor(i/15))&&(boardState[i-step]||pending.has(i-step)))i-=step;let word='',cells=[];while(i>=0&&i<225&&(step===15||!cells.length||Math.floor(i/15)===Math.floor(cells[0]/15))&&(boardState[i]||pending.has(i))){word+=(pending.get(i)?.letter||boardState[i]);cells.push(i);i+=step}return{word,cells}};
function formedWords(){const out=new Map();for(const i of pending.keys())for(const step of [1,15]){const w=lineWord(i,step);if(w.word.length>1)out.set(w.cells.join('-'),w)}return[...out.values()]}
function validPlacement(){const cells=[...pending.keys()];if(!cells.length)return'Letakkan sekurang-kurangnya satu jubin.';const rows=new Set(cells.map(i=>Math.floor(i/15))),cols=new Set(cells.map(i=>i%15));if(rows.size>1&&cols.size>1)return'Jubin baharu mesti berada pada satu baris atau lajur.';const step=rows.size===1?1:15,min=Math.min(...cells),max=Math.max(...cells);for(let i=min;i<=max;i+=step)if(!boardState[i]&&!pending.has(i))return'Tidak boleh ada petak kosong di antara jubin.';if(!boardState.some(Boolean)&&!pending.has(center))return'Perkataan pertama mesti melalui petak bintang.';if(boardState.some(Boolean)&&!cells.some(i=>[i-1,i+1,i-15,i+15].some(n=>n>=0&&n<225&&(Math.abs((n%15)-(i%15))<=1)&&boardState[n])))return'Perkataan mesti bersambung dengan jubin di papan.';return''}
function moveScore(words){let total=0;for(const {cells} of words){let sum=0,mult=1;for(const i of cells){const l=pending.get(i)?.letter||boardState[i],p=pending.has(i)?premium[i]:null;sum+=values[l]*(p==='DL'?2:p==='TL'?3:1);if(p==='DW'||i===center)mult*=2;if(p==='TW')mult*=3}total+=sum*mult}return total+(pending.size===7?50:0)}
function previewMove(){const words=formedWords(),err=validPlacement();$('#wordScore').textContent=err?'0 mata':moveScore(words)+' mata';$('#wordMessage').textContent=pending.size?err||words.map(w=>w.word).join(' + '):'Pilih jubin, kemudian pilih petak papan.'}
renderBoard();renderRack();const typedLabel=$('#wordInput').closest('label');typedLabel.hidden=true;$('.dictionaryNote').textContent='Pilih jubin pada rak, kemudian pilih petak papan. Semua jubin baharu mesti sebaris atau selajur dan bersambung dengan perkataan sedia ada.';const controls=document.createElement('div');controls.className='moveControls';controls.innerHTML='<button id="undoMove">Batalkan Jubin</button><button id="shuffleRack">Kocok Rak</button><button id="passTurn">Lepas Giliran</button>';$('#submitWord').before(controls);$('#submitWord').textContent='Sahkan Pergerakan';
$('#undoMove').onclick=()=>{for(const p of pending.values())rackLetters.push(p.letter);pending.clear();selected=null;renderBoard();renderRack();previewMove()};$('#shuffleRack').onclick=()=>{rackLetters.sort(()=>Math.random()-.5);selected=null;renderRack()};$('#passTurn').onclick=()=>{$('#wordMessage').textContent='Giliran dilepaskan. Menunggu pihak lawan…'};
$('#submitWord').onclick=()=>{const err=validPlacement(),words=formedWords(),invalid=words.filter(w=>!accepted.has(w.word));if(err){$('#wordMessage').textContent=err;return}if(!words.length){$('#wordMessage').textContent='Pergerakan ini tidak membentuk perkataan.';return}if(invalid.length){$('#wordMessage').textContent=invalid.map(w=>w.word).join(', ')+' belum ditemui dalam kamus.';$('#challengeBtn').hidden=false;return}const pts=moveScore(words);for(const[i,p]of pending)boardState[i]=p.letter;pending.clear();while(rackLetters.length<7)rackLetters.push(draw());score+=pts;$('#myScore').textContent=score;$('#wordMessage').textContent=`✓ ${words.map(w=>w.word).join(' + ')} · +${pts} mata`;$('#wordScore').textContent='0 mata';$('#challengeBtn').hidden=true;renderBoard();renderRack()};
const cfg=window.SAHIBBA_FIREBASE_CONFIG||{},configured=Object.values(cfg).every(Boolean),superEmail='mradnanmahmud@gmail.com',permitted=e=>e===superEmail||e.endsWith('@moe.edu.sg')||e.endsWith('@schools.gov.sg');if(!configured)$('#configNote').hidden=false;
if(configured){
 const {initializeApp}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),{getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),{getFirestore,doc,getDoc,setDoc,updateDoc,serverTimestamp,collection,onSnapshot,increment,arrayUnion}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');
 const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});let currentUser,currentCode,players=[],stopPlayers;
 onSnapshot(collection(db,'globalDictionary'),s=>s.docs.forEach(d=>accepted.add(d.id.toUpperCase())));
 function dictionary(user){let p=$('#sharedDictionary');if(!p){p=document.createElement('section');p.id='sharedDictionary';p.className='panel';p.style.marginTop='18px';$('#reviewsPanel').after(p)}p.innerHTML='<div class="panelHead"><div><p class="eyebrow">KAMUS SAHIBBA GLOBAL</p><h2>Lulus dan kongsi perkataan</h2></div><span class="live" id="globalCount">0 PERKATAAN</span></div><p>Perkataan yang diluluskan boleh digunakan dalam semua kelas.</p><div class="dictionaryForm"><input id="approveWord" placeholder="Contoh: MENGGAMIT"><button class="primary compact" id="approveGlobal">Lulus & Tambah</button></div><p id="dictionaryStatus" class="eyebrow"></p>';onSnapshot(collection(db,'globalDictionary'),s=>$('#globalCount').textContent=s.size+' PERKATAAN');$('#approveGlobal').onclick=async()=>{const w=$('#approveWord').value.toUpperCase().replace(/[^A-Z]/g,'');if(w.length<2)return;await setDoc(doc(db,'globalDictionary',w),{word:w,approvalCount:increment(1),approvedBy:arrayUnion(user.uid),lastApprovedBy:user.email,lastApprovedAt:serverTimestamp()},{merge:true});accepted.add(w);$('#dictionaryStatus').textContent=w+' telah ditambah.';$('#approveWord').value=''}}
 function watch(code){currentCode=code;localStorage.setItem('sahibbaActiveSession',code);onSnapshot(doc(db,'publicSessions',code),s=>{if(!s.exists())return;const d=s.data();$('#classTitle').textContent=d.className;$('#sessionLabel').textContent='Kod sesi '+code;$('#playerLimit').textContent='/'+d.maxPlayers;$('#startMatches').disabled=d.status==='playing';$('#startMatches').textContent=d.status==='playing'?'Permainan Bermula':'Mulakan Padanan';$('#liveBadge').textContent=d.status==='playing'?'● LANGSUNG':'MENUNGGU';$('#matchStatus').textContent=d.status==='playing'?'● Sedang berlangsung':'◷ Belum dimulakan'});if(stopPlayers)stopPlayers();stopPlayers=onSnapshot(collection(db,'publicSessions',code,'players'),s=>{players=s.docs.map(d=>({id:d.id,...d.data()}));$('#playerCount').textContent=players.length;$('#playerStatus').textContent=players.length?players.map(p=>p.name).join(', '):'Kongsi kod sesi dengan murid'})}
 joinSession=async(code,name)=>{const s=await getDoc(doc(db,'publicSessions',code));if(!s.exists())throw Error('Kod sesi tidak ditemui.');if(s.data().status==='playing')throw Error('Permainan sudah bermula.');const id=crypto.randomUUID?.()||Date.now()+'';await setDoc(doc(db,'publicSessions',code,'players',id),{name,score:0,joinedAt:serverTimestamp()})};
 $('#newClass').onclick=()=>$('#classDialog').showModal();$('#classForm').onsubmit=async e=>{e.preventDefault();const name=$('#className').value.trim(),limit=Number($('#maxPlayers').value);try{let code,s;do{code=String(Math.floor(1000+Math.random()*9000));s=await getDoc(doc(db,'publicSessions',code))}while(s.exists());await setDoc(doc(db,'publicSessions',code),{teacherId:currentUser.uid,teacherEmail:currentUser.email,className:name,maxPlayers:limit,status:'waiting',createdAt:serverTimestamp(),validWords:0,reviewCount:0});$('#classDialog').close();watch(code)}catch(err){$('#classError').textContent=err.message}};
 $('#startMatches').onclick=async()=>{if(!currentCode||players.length<2){alert('Sekurang-kurangnya 2 murid perlu masuk.');return}const a=[...players].sort(()=>Math.random()-.5),pairs=[];for(let i=0;i<a.length-1;i+=2){const p=a[i],q=a[i+1];await setDoc(doc(db,'publicSessions',currentCode,'matches',p.id+'_'+q.id),{player1Id:p.id,player1Name:p.name,player2Id:q.id,player2Name:q.name,score1:0,score2:0,turn:p.id,status:'playing',createdAt:serverTimestamp()});pairs.push([p,q])}await updateDoc(doc(db,'publicSessions',currentCode),{status:'playing',startedAt:serverTimestamp()});$('#matchCount').textContent=pairs.length;$('#matchesTable').innerHTML='<div class="tableHead"><span>PADANAN</span><span>SKOR</span><span>GILIRAN</span><span>STATUS</span></div>'+pairs.map(([p,q])=>`<button><span><b>${p.name}</b> lwn ${q.name}</span><strong>0–0</strong><span>${p.name}</span><em>● Bermain</em></button>`).join('')};
 $$('.sideNav nav button').forEach(b=>b.onclick=()=>{$$('.sideNav nav button').forEach(x=>x.classList.toggle('active',x===b));$('#'+b.dataset.section)?.scrollIntoView({behavior:'smooth'})});
 async function enter(user){const email=(user.email||'').toLowerCase();if(!permitted(email)){await signOut(auth);throw Error('Pendaftaran hanya untuk akaun @moe.edu.sg atau @schools.gov.sg.')}currentUser=user;const role=email===superEmail?'superuser':'teacher';await setDoc(doc(db,'teachers',user.uid),{uid:user.uid,email,displayName:user.displayName||'Guru',role,lastLoginAt:serverTimestamp()},{merge:true});$('#teacherName').textContent=user.displayName||'Guru';$('#teacherEmail').textContent=email;dictionary(user);const saved=localStorage.getItem('sahibbaActiveSession');if(saved){const s=await getDoc(doc(db,'publicSessions',saved));if(s.exists()&&(s.data().teacherId===user.uid||role==='superuser'))watch(saved)}show('dashboard')}
 $('#googleLogin').onclick=async()=>{try{await enter((await signInWithPopup(auth,provider)).user)}catch(e){$('#authError').hidden=false;$('#authError').textContent=e.message}};onAuthStateChanged(auth,u=>{if(u&&permitted((u.email||'').toLowerCase())&&location.hash==='#dashboard')enter(u).catch(()=>show('teacher'))});$('#logout').onclick=async()=>{await signOut(auth);show('home')};
}else $('#googleLogin').onclick=()=>$('#configNote').hidden=false;
if(location.hash)show(location.hash.slice(1));
